# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg2a.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg2a.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('Z\rxmit.analysis'),
  serialized_pb=_b('\n\x0bmsg2a.proto\"s\n\x05Msg2A\x12\x15\n\rtimestampsend\x18\x01 \x01(\x04\x12\x15\n\rtimestamprecv\x18\x06 \x01(\x04\x12\x0b\n\x03seq\x18\x02 \x01(\x04\x12\x10\n\x08mismatch\x18\x03 \x01(\x08\x12\x0f\n\x07msgtype\x18\x04 \x01(\x04\x12\x0c\n\x04size\x18\x05 \x01(\x04\x42\x0fZ\rxmit.analysisb\x06proto3')
)




_MSG2A = _descriptor.Descriptor(
  name='Msg2A',
  full_name='Msg2A',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestampsend', full_name='Msg2A.timestampsend', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamprecv', full_name='Msg2A.timestamprecv', index=1,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq', full_name='Msg2A.seq', index=2,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mismatch', full_name='Msg2A.mismatch', index=3,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgtype', full_name='Msg2A.msgtype', index=4,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='Msg2A.size', index=5,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['Msg2A'] = _MSG2A
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Msg2A = _reflection.GeneratedProtocolMessageType('Msg2A', (_message.Message,), dict(
  DESCRIPTOR = _MSG2A,
  __module__ = 'msg2a_pb2'
  # @@protoc_insertion_point(class_scope:Msg2A)
  ))
_sym_db.RegisterMessage(Msg2A)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
