// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: msg2a.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg2A struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestampsend uint64 `protobuf:"varint,1,opt,name=timestampsend,proto3" json:"timestampsend,omitempty"`
	Timestamprecv uint64 `protobuf:"varint,6,opt,name=timestamprecv,proto3" json:"timestamprecv,omitempty"`
	Seq           uint64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Mismatch      bool   `protobuf:"varint,3,opt,name=mismatch,proto3" json:"mismatch,omitempty"`
	Msgtype       uint64 `protobuf:"varint,4,opt,name=msgtype,proto3" json:"msgtype,omitempty"`
	Size          uint64 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Msg2A) Reset() {
	*x = Msg2A{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg2a_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg2A) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg2A) ProtoMessage() {}

func (x *Msg2A) ProtoReflect() protoreflect.Message {
	mi := &file_msg2a_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg2A.ProtoReflect.Descriptor instead.
func (*Msg2A) Descriptor() ([]byte, []int) {
	return file_msg2a_proto_rawDescGZIP(), []int{0}
}

func (x *Msg2A) GetTimestampsend() uint64 {
	if x != nil {
		return x.Timestampsend
	}
	return 0
}

func (x *Msg2A) GetTimestamprecv() uint64 {
	if x != nil {
		return x.Timestamprecv
	}
	return 0
}

func (x *Msg2A) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Msg2A) GetMismatch() bool {
	if x != nil {
		return x.Mismatch
	}
	return false
}

func (x *Msg2A) GetMsgtype() uint64 {
	if x != nil {
		return x.Msgtype
	}
	return 0
}

func (x *Msg2A) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_msg2a_proto protoreflect.FileDescriptor

var file_msg2a_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x32, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d,
	0x61, 0x69, 0x6e, 0x22, 0xaf, 0x01, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x32, 0x41, 0x12, 0x24, 0x0a,
	0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x65, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73,
	0x65, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x72, 0x65, 0x63, 0x76, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x72, 0x65, 0x63, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6d,
	0x69, 0x73, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6d,
	0x69, 0x73, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x78, 0x6d, 0x69, 0x74, 0x2e, 0x61, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg2a_proto_rawDescOnce sync.Once
	file_msg2a_proto_rawDescData = file_msg2a_proto_rawDesc
)

func file_msg2a_proto_rawDescGZIP() []byte {
	file_msg2a_proto_rawDescOnce.Do(func() {
		file_msg2a_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg2a_proto_rawDescData)
	})
	return file_msg2a_proto_rawDescData
}

var file_msg2a_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_msg2a_proto_goTypes = []interface{}{
	(*Msg2A)(nil), // 0: main.Msg2A
}
var file_msg2a_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msg2a_proto_init() }
func file_msg2a_proto_init() {
	if File_msg2a_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg2a_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg2A); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg2a_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg2a_proto_goTypes,
		DependencyIndexes: file_msg2a_proto_depIdxs,
		MessageInfos:      file_msg2a_proto_msgTypes,
	}.Build()
	File_msg2a_proto = out.File
	file_msg2a_proto_rawDesc = nil
	file_msg2a_proto_goTypes = nil
	file_msg2a_proto_depIdxs = nil
}
